name: 'nightly artifacts cleanup 2'
on:
  schedule:
    - cron:   '20 15 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: $
          expire-in: 0days # Set this to 0 to delete all artifacts
