name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron:   '13 15 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: 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
          expire-in: 0days # Set this to 0 to delete all artifacts
